# [dbo].[CLIENTES]

In [0]:
USE [MI_BASE_DE_DATOS]
GO

In [0]:
/****** Object:  Table [dbo].[CLIENTES]    Script Date: 03/10/2022 19:46:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTES](
	[ID_Clientes] [int] IDENTITY(1,1) NOT NULL,
	[Apellido] [nvarchar](50) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Dni] [nvarchar](50) NOT NULL,
	[ID_Localidad] [int] NOT NULL,
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED 
(
	[ID_Clientes] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[COMPRA]

In [0]:
/****** Object:  Table [dbo].[COMPRA]    Script Date: 03/10/2022 19:46:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPRA](
	[ID_Compra] [int] IDENTITY(1,1) NOT NULL,
	[ID_Cuenta] [int] NOT NULL,
	[Monto] [money] NOT NULL,
	[Fecha] [date] NOT NULL,
 CONSTRAINT [PK_COMPRA] PRIMARY KEY CLUSTERED 
(
	[ID_Compra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[CUENTA]

In [0]:
/****** Object:  Table [dbo].[CUENTA]    Script Date: 03/10/2022 19:46:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUENTA](
	[ID_Cuenta] [int] IDENTITY(1,1) NOT NULL,
	[CVUCliente] [nvarchar](50) NOT NULL,
	[ID_Cliente] [int] NOT NULL,
	[ID_Moneda] [int] NOT NULL,
	[Saldo] [money] NOT NULL,
 CONSTRAINT [PK_CUENTA] PRIMARY KEY CLUSTERED 
(
	[ID_Cuenta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[CUENTA_DESTINO]

In [0]:
/****** Object:  Table [dbo].[CUENTA_DESTINO]    Script Date: 03/10/2022 19:46:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUENTA_DESTINO](
	[ID_CuentaDestino] [int] IDENTITY(1,1) NOT NULL,
	[CVUdestino] [nvarchar](50) NOT NULL,
	[NombreDestino] [nvarchar](50) NOT NULL,
	[ID_Cliente] [int] NOT NULL,
 CONSTRAINT [PK_CUENTA_DESTINO] PRIMARY KEY CLUSTERED 
(
	[ID_CuentaDestino] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[EMAIL]

In [0]:
/****** Object:  Table [dbo].[EMAIL]    Script Date: 03/10/2022 19:46:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMAIL](
	[Email] [nvarchar](50) NOT NULL,
	[ID_Clientes] [int] NOT NULL,
 CONSTRAINT [PK_EMAIL] PRIMARY KEY CLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[INGRESO]

In [0]:
/****** Object:  Table [dbo].[INGRESO]    Script Date: 03/10/2022 19:46:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INGRESO](
	[ID_Ingreso] [int] IDENTITY(1,1) NOT NULL,
	[ID_Cuenta] [int] NOT NULL,
	[Monto] [money] NOT NULL,
	[Fecha] [date] NULL,
 CONSTRAINT [PK_INGRESO] PRIMARY KEY CLUSTERED 
(
	[ID_Ingreso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[LOCALIDAD]

In [0]:
/****** Object:  Table [dbo].[LOCALIDAD]    Script Date: 03/10/2022 19:46:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOCALIDAD](
	[ID_Localidad] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[ID_Provincia] [int] NOT NULL,
 CONSTRAINT [PK_LOCALIDAD] PRIMARY KEY CLUSTERED 
(
	[ID_Localidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[MONEDA]

In [0]:
/****** Object:  Table [dbo].[MONEDA]    Script Date: 03/10/2022 19:46:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MONEDA](
	[ID_Moneda] [int] IDENTITY(1,1) NOT NULL,
	[NombreMoneda] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MONEDA] PRIMARY KEY CLUSTERED 
(
	[ID_Moneda] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[PROVINCIA]

In [0]:
/****** Object:  Table [dbo].[PROVINCIA]    Script Date: 03/10/2022 19:46:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROVINCIA](
	[ID_Provincia] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_PROVINCIA] PRIMARY KEY CLUSTERED 
(
	[ID_Provincia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TRANSFERENCIA]

In [0]:
/****** Object:  Table [dbo].[TRANSFERENCIA]    Script Date: 03/10/2022 19:46:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRANSFERENCIA](
	[ID_Transferencia] [int] IDENTITY(1,1) NOT NULL,
	[ID_Cuenta] [int] NOT NULL,
	[ID_CuentaDestino] [int] NOT NULL,
	[Monto] [money] NOT NULL,
	[Fecha] [date] NULL,
 CONSTRAINT [PK_TRANSFERENCIA] PRIMARY KEY CLUSTERED 
(
	[ID_Transferencia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[VENTA]

In [0]:
/****** Object:  Table [dbo].[VENTA]    Script Date: 03/10/2022 19:46:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENTA](
	[ID_Venta] [int] IDENTITY(1,1) NOT NULL,
	[ID_Cuenta] [int] NOT NULL,
	[Monto] [money] NOT NULL,
	[Fecha] [date] NOT NULL,
 CONSTRAINT [PK_VENTA] PRIMARY KEY CLUSTERED 
(
	[ID_Venta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO